---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.33.0-standalone-strict/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: glance-dashboard
  name: glance-dashboard
  namespace: glance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: glance-dashboard
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: glance-dashboard
    spec:
      containers:
        - image: docker.io/glanceapp/glance:v0.7.13
          name: glance
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsGroup: 1000
          volumeMounts:
          - name: glance-config
            mountPath: /app/config/
      volumes:
        - name: glance-config
          configMap:
            name: glance