---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.33.0-standalone-strict/service.json
apiVersion: v1
kind: Service
metadata:
  labels:
    app: glance
  name: glance
  namespace: glance
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: glance-dashboard
  type: ClusterIP
