# yaml-language-server: $schema=https://raw.githubusercontent.com/not-first/glance-schema/master/schema.json
columns:
  - size: full
    widgets:
      - type: videos
        channels:
          - UCZNhwA1B5YqiY1nLzmM0ZRg # Christian Lempa
          - UCVRJ6D343dX-x730MRP8tNw # Cocadmin
          - UCp3yVOm6A55nx65STpm3tXQ # Craft Computing
          - UCVy16RS5eEDh8anP8j94G2A # DB Tech
          - UCYeiozh-4QwuC1sjgCmB92w # DevOps Toolbox
          - UCfz8x0lVzJpb_dgWm9kPVrw # DevOps Toolkit
          - UCIFzjAer2W9gTWVECZgtDzg # GaryH Tech
          - UCUUTdohVElFLSP4NBnlPEwA # Jim's Garage
          - UCjCeyHQarZ0gtndcuz4dEkw # Korben
          - UCxQKHvKbmSzGMvUrVtJYnUA # Learn Linux TV
          - UC9x0AN7BWHpCDHSm9NiJFJQ # NetworkChuck
          - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim
          - UC_zBdZ0_H_jn41FDRG7q4Tw # Vimjoyer
          - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
          - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
          - UCsBjURrPoezykLs9EqgamOA # Fireship
          - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
        style: grid-cards